name: Build Game for Windows

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: cmd
      run: |
        python -m pip install --upgrade pip
        # QUAN TRONG: Cai numpy ban cu (<2) de tranh loi man hinh do
        pip install pygame opencv-python mediapipe pymunk "numpy<2" pyinstaller

    - name: Build EXE using PyInstaller
      shell: cmd
      run: |
        # QUAN TRONG: --collect-all mediapipe la lenh bat buoc de AI hoat dong
        pyinstaller --noconsole --onedir --name "ShadowGame" --collect-all mediapipe --hidden-import=mediapipe.python.solutions --hidden-import=mediapipe.framework.formats --hidden-import=mediapipe.framework.formats.landmark_pb2 main.py

    - name: Copy Assets
      shell: cmd
      run: |
        echo "Dang copy file..."
        copy font.ttf dist\ShadowGame\
        if exist highscores.txt copy highscores.txt dist\ShadowGame\
        if exist settings.py copy settings.py dist\ShadowGame\
        xcopy /E /I core dist\ShadowGame\core

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ShadowGame_Windows_Final
        path: dist/ShadowGame/